#!/bin/bash

#[[ $BLOCK_BUTTON = "1" ]] && kitty -1 --class prompt --name floating --hold -e curl -s  wttr.in
[[ $BLOCK_BUTTON = "1" ]] && st -c prompt -n "weather" -g 126x41 bash -c "curl -s  wttr.in && sleep 5"

ping -q -w 1 -c 1 `ip r | grep default | head -n1| cut -d ' ' -f 3` >/dev/null || exit

weatherreport=$(curl -s wttr.in)

precipitation=$(echo "$weatherreport"|sed -n 16p | sed -e 's/[^m]*m//g' | grep -o "[0-9]*%" | sort -n | sed -e '$!d' |sed -e 's/\n//g')
precipitation=" $precipitation"
temperature=$(echo "$weatherreport" | sed -n 13p | sed -e 's/[^m]*m//g;s/[^0-9]/ /g;s/ /\n/g;/^s*$/d' | grep "[0-9]" | sort -n | sed -e 1b -e '$!d' | tr '\n' ' ' | awk '{print "L: ",$1 "°","H: ",$2 "°"}')
echo $precipitation $temperature
