#!/usr/bin/env bash
# used for waybar
#text=`echo $cpu |jq '.["temp1_input"]'`
#temp=${text%.*}
#max=`echo $cpu |jq '.["temp1_max"]'`
#class="cool"
#if [[ temp -gt 55 ]]; then
#    class="normal"
#    elif [[ temp -gt 60 ]]; then
#        class="critical"
#fi
##echo "{\"text\": \"$text\", \"tooltip\": \"$tooltip\", \"class\": \"$class\", \"percentage\": $percentage }" | jq --unbuffered --compact-output
sensor=`sensors -j 2>/dev/null`
# cpu=`echo "$sensor" | jq '.["k10temp-pci-00c3"]|.["Tctl"]|.["temp1_input"]'`
cpu=`echo "$sensor" | jq '[.[]|.[]]|.[1]|.["temp1_input"]'`
# gpu=`echo "$sensor" | jq '.["amdgpu-pci-0300"]|.["edge"]|.["temp1_input"]'`
tooltip=$( sensors -A )
cpu=${cpu%.*}
max=75
percentage=`echo "$cpu/$max*100" |bc -l`
# gpu=${gpu%.*}
class="cool"
#echo  "C/G:$cpu/$gpu °C"
# echo  "$cpu °C"
#echo  "$cpu/$gpu °C"
# echo  "$cpu °C"
if [[ $cpu -gt 50 ]]; then
    class="normal"
    # echo  \#FFFC00
    elif [[ $cpu -gt 60 ]]; then
        class="critical"
        # echo \#FF0000
fi
echo "{\"text\": \"$cpu\", \"tooltip\": \"$tooltip\", \"class\": \"$class\", \"percentage\": $percentage}"|sed  ':a;N;$!ba;s/\n/\\n/g'
# echo -e "$cpu\n$tooltip\n$class"
