---
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    # environment:
      # Optional: put your config options customization here. Examples:
      # ND_LOGLEVEL: debug
    volumes:
      - "/storage/appdata/navidrome:/data"
      - "/storage/Music/HiRes:/music:ro"
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Asia/Hong_Kong
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Hong_Kong
    volumes:
      - /storage/appdata/prowlarr:/config
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /storage/appdata/jacket:/config
      # - /path/to/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
    volumes:
      # - lidarrdata:/config
      # - music:/music #optional
      # - downloads:/downloads #optional
      - /storage/appdata/lidarr:/config
      - /storage/Music/HiRes:/music #optional
      - /storage/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped

  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
    volumes:
      # - rdtdata:/data
      # - downloads:/downloads
      - /storage/appdata/rdt:/data
      - /storage/downloads:/downloads #optional
    logging:
       driver: json-file
       options:
          max-size: 10m
    ports:
      - 6500:6500
    restart: unless-stopped

# volumes:
#   music:
#     name: music
#     driver: "local"
#     driver_opts:
#       type: nfs4
#       o: "addr=192.168.8.8,rw"
#       device: ":/storage/Music/HiRes"
#   rdtdata:
#     name: rdtdata
#     driver: "local"
#     driver_opts:
#       type: nfs4
#       o: "addr=192.168.8.8,rw"
#       device: ":/storage/appdata/rdt"
#   lidarrdata:
#     name: lidarrdata
#     driver: "local"
#     driver_opts:
#       type: nfs4
#       o: "addr=192.168.8.8,rw"
#       device: ":/storage/appdata/lidarr"
#   downloads:
#     name: downloads
#     driver: "local"
#     driver_opts:
#       type: nfs4
#       o: "addr=192.168.8.8,rw"
#       device: ":/storage/downloads"
