---
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /storage/appdata/jacket:/config
      # - /path/to/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
    volumes:
      # - lidarrdata:/config
      # - music:/music #optional
      # - downloads:/downloads #optional
      - /storage/appdata/lidarr:/config
      - /storage/Music/HiRes:/music #optional
      - /storage/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped

  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
    volumes:
      # - rdtdata:/data
      # - downloads:/downloads
      - /storage/appdata/rdt:/data
      - /storage/downloads:/downloads #optional
    logging:
       driver: json-file
       options:
          max-size: 10m
    ports:
      - 6500:6500
    restart: unless-stopped

# volumes:
#   music:
#     name: music
#     driver: "local"
#     driver_opts:
#       type: nfs4
#       o: "addr=192.168.8.8,rw"
#       device: ":/storage/Music/HiRes"
#   rdtdata:
#     name: rdtdata
#     driver: "local"
#     driver_opts:
#       type: nfs4
#       o: "addr=192.168.8.8,rw"
#       device: ":/storage/appdata/rdt"
#   lidarrdata:
#     name: lidarrdata
#     driver: "local"
#     driver_opts:
#       type: nfs4
#       o: "addr=192.168.8.8,rw"
#       device: ":/storage/appdata/lidarr"
#   downloads:
#     name: downloads
#     driver: "local"
#     driver_opts:
#       type: nfs4
#       o: "addr=192.168.8.8,rw"
#       device: ":/storage/downloads"
