#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

## autostart, don't forget to fork the process or it will block
#
#
# export XDG_CURRENT_DESKTOP=river
export XDG_CURRENT_DESKTOP=sway
import-gsettings
#clear buttons to hide gtk titlebar, needs to leave menu to prevent crash in microsoft edge
gsettings set org.gnome.desktop.wm.preferences button-layout "menu:"
wl-paste -t text --watch clipman store &
fcitx5 -d --replace
udiskie &
#dunst is started with dubs so no longer needed.
# bash -c "pkill -f dunst; dunst" &
/usr/bin/kanshi &
waybar > waybar.log 2>&1 &
# files=(~/Pictures/wallpaper/*); pkill swaybg ; swaybg -i "${files[RANDOM % ${#files[@]}]}" &
desk_dash.sh &
oguri &
# systemctl --user import-environment DISPLAY WAYLAND_DISPLAY QT_QPA_PLATFORMTHEME
# following bus cmd can replace above, and also import envs to dbus session.
# gnupg needs this to show pinentry correctly, theme, scale etc. Personal
# systemd unit/timers may also depend on DISPLAY, etc.
dbus-update-activation-environment --systemd --all &
nice -12 ~/.dropbox-dist/dropboxd >/dev/null 2>&1 &
lxqt-policykit-agent &
# ## exec --no-startup-id mpris-proxy

# setup variables 
mod="Mod5"
menu="rofi -show combi -m -4"
term="alacritty"
ft="$term --class floating"
browser="qutebrowser"

# Mod+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
riverctl map normal $mod Return spawn "$term"

# mac style spotlight/search hotkey using cmd+space
riverctl map normal Control Space spawn "$menu"

# Mod+Q to close the focused view
riverctl map normal Control Q close

# Mod+Shift+E to exit river
riverctl map normal $mod+Shift E exit

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# Mod+Space to bump the focused view to the top of the layout stack
riverctl map normal $mod Space zoom

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# Mod+Alt+{H,J,K,L} to move views
riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Mod1+Control H snap left
riverctl map normal $mod+Mod1+Control J snap down
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod $i set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Mod+Shift Space to toggle float
riverctl map normal $mod+Shift Space toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# Mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'volume +5%'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'volume -5%'
    riverctl map $mode None XF86AudioMute         spawn 'volume mute'
    riverctl map $mode None XF86AudioMicMute      spawn 'micmute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'mpc toggle'
    riverctl map $mode None XF86AudioPrev  spawn 'mpc prev'
    riverctl map $mode None XF86AudioNext  spawn 'mpc next'

    # Control screen backlight brighness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightness 1%+'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightness 1%-'

    # personal hotkeys to launch various apps
    riverctl map $mode $mod A spawn "$ft -e gotop"
    # riverctl map $mode Alt p spawn wdisplays
    riverctl map $mode $mod W spawn "notify-send -i 'computer' 'Unsplash:' 'Changing Wallpaper ...' && unsplashwallpaper"
    riverctl map $mode $mod+Shift W spawn "rofi-surfraw"
    riverctl map $mode $mod S spawn "term_hold yay -Syu"
    riverctl map $mode $mod C spawn "$ft -e vim .config/river/init"
    riverctl map $mode $mod M spawn "$ft -e neomutt"
    riverctl map $mode $mod T spawn "$ft -e tmux_run.sh"
    riverctl map $mode $mod D spawn "$ft -e vim -c :VimwikiDiaryIndex"
    riverctl map $mode $mod R spawn "$ft -e rtv"
    riverctl map $mode $mod N spawn "kitty --class floating --listen-on=unix:/tmp/mykitty -e nnn -ed -P P"
    riverctl map $mode $mod X spawn "$ft -e journalctl -xe"
    riverctl map $mode $mod+Shift X spawn "$ft -e journalctl -k"
    riverctl map $mode $mod V spawn "clipman pick -t rofi"
    riverctl map $mode $mod B spawn "papis -s picktool rofi open"
    riverctl map $mode $mod z spawn "pkill -12 nwg-wrapper"
    # control dunst notification
    riverctl map $mode Control grave spawn "dunstctl history-pop"
    riverctl map $mode None Print spawn "snapshot full"
    riverctl map $mode Shift Print spawn "snapshot select"
    riverctl map $mode $mod+Shift L spawn "swaylock & systemctl suspend"
    riverctl map $mode Control+Shift 3 spawn "snapshot full"
    riverctl map $mode Control+Shift 4 spawn "snapshot select"
done

# Set background and border color

riverctl background-color 0x404552
riverctl border-color-focused 0x2e9ef4
riverctl border-color-unfocused 0x08080800

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
riverctl float-filter-add app-id floating
riverctl float-filter-add app-id "msedge-www.merriam-webster.com"
riverctl float-filter-add app-id floatingv
riverctl float-filter-add app-id "pinentry-qt"
riverctl float-filter-add app-id ncmpcpp
riverctl float-filter-add app-id "imv"
riverctl float-filter-add app-id "display"
riverctl float-filter-add app-id "mpv"
riverctl float-filter-add app-id "vlc"
riverctl float-filter-add app-id "pavucontrol"
riverctl float-filter-add app-id "wpa_gui"
riverctl float-filter-add app-id "neomutt"
riverctl float-filter-add app-id "kvantummanager"
riverctl float-filter-add app-id "dolphin-emu"
riverctl float-filter-add title "Fcitx Configuration"
riverctl float-filter-add title "Firefox Developer Edition — Sharing Indicator"
riverctl float-filter-add title "Save file"
riverctl float-filter-add title "nnn"
riverctl float-filter-add app-id Lxappearance
riverctl float-filter-add app-id lxqt-policykit-agent

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"
riverctl csd-filter-add app-id "refoxdeveloperedition"

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile

#focus and cursor settings

# riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change

#input settings

riverctl input "pointer-1739-52542-MSFT0001:00_06CB:CD3E_Touchpad" disable-while-typing enabled
riverctl input "pointer-1739-52542-MSFT0001:00_06CB:CD3E_Touchpad" tap enabled
riverctl input "pointer-1739-52542-MSFT0001:00_06CB:CD3E_Touchpad" natural-scroll enabled
riverctl input "pointer-1739-52542-MSFT0001:00_06CB:CD3E_Touchpad" middle-emulation enabled
riverctl input "pointer-1739-52542-MSFT0001:00_06CB:CD3E_Touchpad" pointer-accel 0.05
# riverctl input "1739:52542:MSFT0001:00_06CB:CD3E_Touchpad" scroll-factor 0.3
       #accel_profile adaptive

exec rivertile -view-padding 6 -outer-padding 6
