[colors.primary]
background = "#303446"
foreground = "#c6d0f5"
dim_foreground = "#838ba7"
bright_foreground = "#c6d0f5"

[colors.normal]
black = "#1E1D2F"
red = "#dc322f"
yellow = "#b58900"
green = "#859900"
blue = "#268bd2"
magenta = "#d33682"
cyan = "#2aa198"
white = "#eee8d5"

[colors.bright]
black = "#3d4c5f"
red = "#cb4b16"
yellow = "#657b83"
green = "#586e75"
blue = "#839496"
magenta = "#6c71c4"
cyan = "#8cc7d6"
white = "#a1d4c7"

