[colors.primary]
background = "#303446"
foreground = "#c6d0f5"
dim_foreground = "#838ba7"
bright_foreground = "#c6d0f5"

[colors.bright]
black = "#3d4c5f"
blue = "0x839496"
cyan = "#8cc7d6"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "#a1d4c7"
yellow = "0x657b83"

[colors.normal]
black = "#1E1D2F"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"
